
model:
  name: lora_dcvcrt_image 
  N: 256
  z_channel: 128
  pretrained: null 


train:
  epochs: 50
  val_multi_qp_list: [0]
  seed: 8047 
  gpu_id: 0 
  warmup_epochs: 1
  val_multi_qp_interval: 100000
  resume: true 
  clip_max_norm: 1.0
  
dataset:
  train_dataset:
    root_dir: ""
    patch_size: [256, 256]
    is_train: true 
    color_space: "ycbcr"
    norm: false 
  eval_dataset:
    root_dir: ""
    patch_size: [256, 256]
    is_train: false 
    color_space: "ycbcr"
    norm: false 
  batch_size: 16
  eval_batch_size: 1
  num_workers: 8


optim:
  g_optimizer:
    name: adamw
    lr: 0.00002
  d_optimizer:
    name: adamw 
    lr: 0.0001


losses:
  gan_loss:
    loss_weight: 1.0 
    real_label: 1.0
    fake_label: 0.0
  perceptual_loss:
    loss_weight: 1.0
    range_norm: true 
    net: "alex"
  perceptual_loss_weight: 1.0
  gen_loss_weight: 0.002
  distortion_loss_weight: 150 


discriminator:
  in_ch: 3
  out_ch: 1
  main_ch: 64
  y_ch: 256
  latent_nc: 16 


save_dir: "./checkpoints/lora_image_percept"

